<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Login_Verification</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>71c035ff-d100-4b34-81a4-51fc0e8bc13a</testSuiteGuid>
   <testCaseLink>
      <guid>167f108e-6db4-4ca9-95d2-19c1c5b14041</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Login_DDT</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f761d7c6-6352-433b-8597-afa3de4c4e8b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data_Excel_Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f761d7c6-6352-433b-8597-afa3de4c4e8b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>8740b694-4a18-48e7-af21-b1686382fa89</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f761d7c6-6352-433b-8597-afa3de4c4e8b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>729857ac-8b34-4bc2-bb91-e1d57fa402c2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
